apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-helloworld
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: node-helloworld
    spec:
      containers:
      - name: node-helloworld
        image: jengademos.azurecr.io/node-helloworld:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: node-helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: node-helloworld